from collections.abc import Awaitable

from httpx import AsyncClient
from httpx import Client
from httpx import Request
from httpx import Response as Response

from .enums.language import Language as Language
from .enums.notification_type import NotificationType as NotificationType
from .enums.path import Path as Path
from .id import GlobalId as GlobalId
from .id import Id as Id
from .models import AllGameBasicInfo as AllGameBasicInfo
from .models import GameBranches as GameBranches
from .models import GameChannelSdks as GameChannelSdks
from .models import GameConfigs as GameConfigs
from .models import GameContent as GameContent
from .models import GameDeprecatedFileConfigs as GameDeprecatedFileConfigs
from .models import GamePackages as GamePackages
from .models import GamePlugins as GamePlugins
from .models import Games as Games
from .models import GameScanInfo as GameScanInfo
from .models import Notification as Notification
from .models import WpfPackages as WpfPackages
from .models.base import Base as Base
from .models.game import Game as Game
from .models.game_status import GameStatus as GameStatus
from .models.response_body import ResponseBody as ResponseBody

def parse_json_response_as[T: Base](model_type: type[T], response: Response) -> T: ...

class Launcher:
    id: Id
    client: Client

    def __init__(self, id: Id = ..., *, client: Client | None = None) -> None: ...
    def _get_request(
        self,
        path: Path,
        *game_ids: Game | GameStatus,
        game_id: Game | GameStatus | None,
        type_: NotificationType | None,
        language: Language | None,
    ) -> Request: ...
    def _get_response(self, request: Request) -> Response: ...
    def _get_data[T: Base](
        self,
        path: Path,
        *game_ids: Game | GameStatus,
        game_id: Game | GameStatus | None = None,
        type_: NotificationType | None = None,
        language: Language | None = None,
        data: type[T],
    ) -> T | None: ...
    def get_game_configs(self, *game_ids: Game | GameStatus) -> GameConfigs: ...
    def get_game_channel_sdks(self, *game_ids: Game | GameStatus) -> GameChannelSdks: ...
    def get_game_deprecated_file_configs(self, *game_ids: Game | GameStatus) -> GameDeprecatedFileConfigs: ...
    def get_game_branches(self, *game_ids: Game | GameStatus) -> GameBranches: ...
    def get_game_packages(self, *game_ids: Game | GameStatus) -> GamePackages: ...
    def get_wpf_packages(self, *game_ids: Game | GameStatus) -> WpfPackages: ...
    def get_game_plugins(self, *game_ids: Game | GameStatus) -> GamePlugins: ...
    def get_games(self) -> Games: ...
    def get_game_scan_info(self, *game_ids: Game | GameStatus) -> GameScanInfo: ...
    def get_game_content(self, game_id: Game | GameStatus, language: Language | None = None) -> GameContent: ...
    def get_all_game_basic_info(self, game_id: Game | GameStatus | None = None) -> AllGameBasicInfo: ...
    def get_notification(self, type: NotificationType | None = None) -> Notification: ...  # noqa: A002

class AsyncLauncher(Launcher):
    client: AsyncClient

    def __init__(self, *, client: AsyncClient | None = None) -> None: ...
    async def _get_response(self, request: Request) -> Response: ...
    async def _get_data[T: Base](
        self,
        path: Path,
        *game_ids: Game | GameStatus,
        game_id: Game | GameStatus | None = None,
        type_: NotificationType | None = None,
        language: Language | None = None,
        data: type[T],
    ) -> T | None: ...
    def get_game_configs(self, *game_ids: Game | GameStatus) -> Awaitable[GameConfigs]: ...
    def get_game_channel_sdks(self, *game_ids: Game | GameStatus) -> Awaitable[GameChannelSdks]: ...
    def get_game_deprecated_file_configs(
        self, *game_ids: Game | GameStatus
    ) -> Awaitable[GameDeprecatedFileConfigs]: ...
    def get_game_branches(self, *game_ids: Game | GameStatus) -> Awaitable[GameBranches]: ...
    def get_game_packages(self, *game_ids: Game | GameStatus) -> Awaitable[GamePackages]: ...
    def get_wpf_packages(self, *game_ids: Game | GameStatus) -> Awaitable[WpfPackages]: ...
    def get_game_plugins(self, *game_ids: Game | GameStatus) -> Awaitable[GamePlugins]: ...
    def get_games(self) -> Awaitable[Games]: ...
    def get_game_scan_info(self, *game_ids: Game | GameStatus) -> Awaitable[GameScanInfo]: ...
    def get_game_content(
        self, game_id: Game | GameStatus, language: Language | None = None
    ) -> Awaitable[GameContent]: ...
    def get_all_game_basic_info(self, game_id: Game | GameStatus | None = None) -> Awaitable[AllGameBasicInfo]: ...
    def get_notification(self, type: NotificationType | None = None) -> Awaitable[Notification]: ...  # noqa: A002
